name: Dockerfile Check

on: [push]

jobs:
  changed_files:
    runs-on: ubuntu-24.04
    name: Test for updated Dockerfiles
    steps:
      - uses: actions/checkout@v4
      - name: Get changed Dockerfiles
        id: changed-dockerfiles
        uses: tj-actions/changed-files@v45
        with:
          files: |
            **/Dockerfile

      - name: Test building images from Dockerfiles
        if: steps.changed-dockerfiles.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-dockerfiles.outputs.all_changed_files }}
        run: |
          echo "----------- Testing Dockerfiles -----------"
          for file in ${ALL_CHANGED_FILES}; do
            echo "TEST: Building Dockerfile: $file"
            docker build -t test:test -f $file . &> /dev/null
            docker rmi test:test &> /dev/null
            echo "SUCCESS: Built Dockerfile: $file"
          done
          echo "-------------------------------------------"
            
