name: Dockerfile Check
# https://stackoverflow.com/a/74268200
on: [push]

jobs:
  check_changed_dockerfiles:
    runs-on: ubuntu-24.04
    name: Test for updated Dockerfiles
    outputs:
      changed_files: ${{ steps.dockerfiles.outputs.changed_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Get changed Dockerfiles
        id: dockerfiles
        run: |
          echo "changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep Dockerfile | xargs | tr -d '\n" ' | jq -s -R 'split(" ")' | jq -r tostring)" >> $GITHUB_OUTPUT

  build_changed_dockerfiles:
    needs: check_changed_dockerfiles
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        job_name: ${{ fromJson(needs.check_changed_dockerfiles.outputs.changed_files) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Test building images from changed Dockerfiles
        run: |
          echo "TESTING: Building Dockerfile: ${{ matrix.job_name }}"
          docker build -t test:test -f ${{ matrix.job_name }} .
          docker rmi test:test &> /dev/null
          echo "SUCCESS: Built Dockerfile: ${{ matrix.job_name }}"
